export const RESET_STATE = 'CUSTOM_RESET_STATE';
export const CURRENT_ITEM = 'CUSTOM_CURRENT_ITEM';

export const REQUEST_LOADING = 'CUSTOM_REQUEST_LOADING';
export const REQUEST_SUCCESS = 'CUSTOM_REQUEST_SUCCESS';
export const REQUEST_FAILED = 'CUSTOM_REQUEST_FAILED';

export const CURRENT_ACTION = 'CUSTOM_CURRENT_ACTION';
export const RESET_ACTION = 'CUSTOM_RESET_ACTION';
